import type { Metadata } from "next";
import CommonLayout from "./_components/template/CommonLayout/commonLayout";
import "@/styles/index.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode,
  modal: React.ReactNode,
}

export default function RootLayout({
  children, modal
}: Props) {
  return (
    <html lang="en">
      <body>
          <CommonLayout>
            {children}
            {modal}
          </CommonLayout>
        </body>
    </html>
  );
}
